name: Digital Ocean deploy

on: 
  registry_package:
  workflow_dispatch:

jobs:
  deploy-to-do:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Get App ID
        run: |
          export DO_APP_ID=$( doctl apps list --no-header --format ID )
          docker pull docker.pkg.github.com/amaximov/shapes-api/image:latest
          doctl registry login
          docker tag image registry.digitalocean.com/shapes/api
          docker push registry.digitalocean.com/shapes/api
          doctl apps create-deployment "$DO_APP_ID"
