name: Digital Ocean deploy

on: 
  registry_package:
  workflow_dispatch:

jobs:
  deploy-to-do:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get App ID
        run: |
          export DO_APP_ID=$( doctl apps list --no-header --format ID )
          docker pull ghcr.io/amaximov/shapes-api/shapes-api-container:latest
          doctl registry login
          docker tag shapes-api-container registry.digitalocean.com/shapes/api
          docker push registry.digitalocean.com/shapes/api
          doctl apps create-deployment "$DO_APP_ID"
