name: Digital Ocean deploy

on: [workflow_dispatch, registry_package]

env:
  GH_CONTAINER: ghcr.io/amaximov/shapes-api/shapes-api-container
  DO_CONTAINER: registry.digitalocean.com/shapes/api

jobs:
  deploy-to-do:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_KEY }}
      - name: Run pull-push-redeploy
        run: |
          export DO_APP_ID=$( doctl apps list --no-header --format ID )
          docker pull $GH_CONTAINER:latest
          doctl registry login
          docker tag $GH_CONTAINER $DO_CONTAINER
          docker push $DO_CONTAINER
          doctl apps create-deployment "$DO_APP_ID"
